#!/bin/bash

echo "=== PostgreSQL Database Setup for Doctor Appointment System ==="
echo ""
echo "This script will set up the database for your application."
echo ""

# Method 1: Using existing postgres superuser
echo "Option 1: Quick Setup (using postgres superuser)"
echo "-----------------------------------------------"
echo "Run this in a new terminal:"
echo ""
echo "psql -U postgres -c \"CREATE DATABASE blazorauthdb;\""
echo ""
echo "Then update appsettings.json with:"
echo "  Username=postgres"
echo "  Password=<your_postgres_password>"
echo ""

# Method 2: Create dedicated user
echo "Option 2: Create dedicated user (recommended)"
echo "-----------------------------------------------"
echo "Run these commands in a new terminal:"
echo ""
echo "# Connect to PostgreSQL (may require sudo on Linux)"
echo "psql postgres"
echo ""
echo "# Then run these SQL commands:"
echo "CREATE USER blazoruser WITH PASSWORD 'BlazorPass123!';"
echo "CREATE DATABASE blazorauthdb OWNER blazoruser;"
echo "GRANT ALL PRIVILEGES ON DATABASE blazorauthdb TO blazoruser;"
echo "\\q"
echo ""
echo "Then update appsettings.json with:"
echo "  Username=blazoruser"
echo "  Password=BlazorPass123!"
echo ""

# Method 3: macOS Homebrew default
echo "Option 3: macOS Homebrew Setup"
echo "-----------------------------------------------"
echo "If you installed PostgreSQL via Homebrew, try:"
echo ""
echo "createdb blazorauthdb"
echo ""
echo "Then update appsettings.json with:"
echo "  Username=<your_mac_username>"
echo "  Password="
echo ""

echo "=== After Setup ==="
echo "1. Update the connection string in:"
echo "   BlazorAuthApp.Api/appsettings.json"
echo ""
echo "2. Run the migration:"
echo "   cd BlazorAuthApp.Api"
echo "   dotnet ef database update"
echo ""
echo "3. Start the application!"
