// <auto-generated />
using System;
using BlazorAuthApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorAuthApp.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260222090433_AddFourMoreDoctors")]
    partial class AddFourMoreDoctors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorAuthApp.Api.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CheckedInByAssistantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<bool>("PatientArrived")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PatientArrivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PatientPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentDate");

                    b.HasIndex("CheckedInByAssistantId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BlazorAuthApp.Api.Models.Assistant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ETagBarcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ETagBarcode")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Assistants");
                });

            modelBuilder.Entity("BlazorAuthApp.Api.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsultationFee = 150.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Experienced cardiologist specializing in heart disease prevention and treatment.",
                            Email = "sarah.johnson@hospital.com",
                            FirstName = "Sarah",
                            ImageUrl = "https://ui-avatars.com/api/?name=Sarah+Johnson&background=4F46E5&color=fff&size=200",
                            IsAvailable = true,
                            LastName = "Johnson",
                            Phone = "+1-555-0101",
                            Specialization = "Cardiology",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 2,
                            ConsultationFee = 120.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compassionate pediatrician dedicated to children's health and wellness.",
                            Email = "michael.chen@hospital.com",
                            FirstName = "Michael",
                            ImageUrl = "https://ui-avatars.com/api/?name=Michael+Chen&background=10B981&color=fff&size=200",
                            IsAvailable = true,
                            LastName = "Chen",
                            Phone = "+1-555-0102",
                            Specialization = "Pediatrics",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 3,
                            ConsultationFee = 130.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Expert dermatologist focusing on skin health and cosmetic procedures.",
                            Email = "emily.rodriguez@hospital.com",
                            FirstName = "Emily",
                            ImageUrl = "https://ui-avatars.com/api/?name=Emily+Rodriguez&background=F59E0B&color=fff&size=200",
                            IsAvailable = true,
                            LastName = "Rodriguez",
                            Phone = "+1-555-0103",
                            Specialization = "Dermatology",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 4,
                            ConsultationFee = 160.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Skilled orthopedic surgeon specializing in joint and bone treatments.",
                            Email = "david.patel@hospital.com",
                            FirstName = "David",
                            ImageUrl = "https://ui-avatars.com/api/?name=David+Patel&background=EF4444&color=fff&size=200",
                            IsAvailable = true,
                            LastName = "Patel",
                            Phone = "+1-555-0104",
                            Specialization = "Orthopedics",
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 5,
                            ConsultationFee = 180.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Renowned neurologist with expertise in brain and nervous system disorders.",
                            Email = "lisa.thompson@hospital.com",
                            FirstName = "Lisa",
                            ImageUrl = "https://ui-avatars.com/api/?name=Lisa+Thompson&background=8B5CF6&color=fff&size=200",
                            IsAvailable = true,
                            LastName = "Thompson",
                            Phone = "+1-555-0105",
                            Specialization = "Neurology",
                            YearsOfExperience = 18
                        },
                        new
                        {
                            Id = 6,
                            ConsultationFee = 140.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Expert eye specialist providing comprehensive eye care and vision solutions.",
                            Email = "james.williams@hospital.com",
                            FirstName = "James",
                            ImageUrl = "https://ui-avatars.com/api/?name=James+Williams&background=06B6D4&color=fff&size=200",
                            IsAvailable = true,
                            LastName = "Williams",
                            Phone = "+1-555-0106",
                            Specialization = "Ophthalmology",
                            YearsOfExperience = 14
                        },
                        new
                        {
                            Id = 7,
                            ConsultationFee = 145.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Caring psychiatrist specializing in mental health and emotional well-being.",
                            Email = "maria.garcia@hospital.com",
                            FirstName = "Maria",
                            ImageUrl = "https://ui-avatars.com/api/?name=Maria+Garcia&background=EC4899&color=fff&size=200",
                            IsAvailable = true,
                            LastName = "Garcia",
                            Phone = "+1-555-0107",
                            Specialization = "Psychiatry",
                            YearsOfExperience = 11
                        },
                        new
                        {
                            Id = 8,
                            ConsultationFee = 170.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Highly skilled surgeon with expertise in various surgical procedures.",
                            Email = "robert.lee@hospital.com",
                            FirstName = "Robert",
                            ImageUrl = "https://ui-avatars.com/api/?name=Robert+Lee&background=14B8A6&color=fff&size=200",
                            IsAvailable = true,
                            LastName = "Lee",
                            Phone = "+1-555-0108",
                            Specialization = "General Surgery",
                            YearsOfExperience = 16
                        },
                        new
                        {
                            Id = 9,
                            ConsultationFee = 155.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dedicated endocrinologist treating hormone disorders and metabolic conditions.",
                            Email = "amanda.miller@hospital.com",
                            FirstName = "Amanda",
                            ImageUrl = "https://ui-avatars.com/api/?name=Amanda+Miller&background=F97316&color=fff&size=200",
                            IsAvailable = true,
                            LastName = "Miller",
                            Phone = "+1-555-0109",
                            Specialization = "Endocrinology",
                            YearsOfExperience = 13
                        });
                });

            modelBuilder.Entity("BlazorAuthApp.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorAuthApp.Api.Models.Appointment", b =>
                {
                    b.HasOne("BlazorAuthApp.Api.Models.Assistant", "CheckedInByAssistant")
                        .WithMany("CheckedInAppointments")
                        .HasForeignKey("CheckedInByAssistantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorAuthApp.Api.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorAuthApp.Api.Models.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckedInByAssistant");

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlazorAuthApp.Api.Models.Assistant", b =>
                {
                    b.Navigation("CheckedInAppointments");
                });

            modelBuilder.Entity("BlazorAuthApp.Api.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BlazorAuthApp.Api.Models.User", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
